name: CI

on:
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
  schedule:
    - cron: '0 20 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - 1.76.0
          - nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Downgrade dependencies to minimal versions
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo update -Z minimal-versions

      - name: Show dependency tree
        run: cargo tree

      - name: Run tests (debug)
        run: cargo test --all-features

      - name: Run tests (release)
        run: cargo test --release --all-features
