name: Clippy lints and Rustfmt

on:
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
  schedule:
    - cron: '0 19 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Run Clippy
        run: cargo clippy --lib --tests --all-features -- -D warnings

      - name: Run Rustfmt
        if: ${{ matrix.rust == 'stable' }}
        run: cargo fmt --all -- --check
